// Import types
#pragma rsuse OsString = std::ffi::OsString
#pragma rsuse VecOsString = std::vec::Vec<OsString>
#pragma rsuse PopenConfig = subprocess::PopenConfig
#pragma rsuse Popen = subprocess::Popen
#pragma rsuse PopenResult = subprocess::Result<Popen>
#pragma rsuse ExitStatusResult = subprocess::Result<subprocess::ExitStatus>
// Import methods (theoretically only needed for non-generic languages like C)
#pragma rsuse OsString_from_str = OsString::From<&str>::from
#pragma rsuse OsString_drop = OsString::drop
#pragma rsuse VecOsString_new = VecOsString::new
#pragma rsuse VecOsString_push = VecOsString::push
#pragma rsuse VecOsString_as_slice = VecOsString::as_slice
#pragma rsuse VecOsString_drop = VecOsString::Drop::drop
#pragma rsuse PopenConfig_default = PopenConfig::default
#pragma rsuse Popen_create = Popen::create::<OsString>
#pragma rsuse Popen_wait = Popen::wait
#pragma rsuse Popen_drop = Popen::Drop::drop
#pragma rsuse PopenResult_is_ok = PopenResult::is_ok
#pragma rsuse PopenResult_unwrap = PopenResult::unwrap
#pragma rsuse PopenResult_drop = PopenResult::drop
#pragma rsuse ExitStatusResult_is_ok = ExitStatusResult::is_ok
#pragma rsuse ExitStatusResult_drop = ExitStatusResult::drop
// Import the header generated by the Makefile invoking the tool
#include "rust_deps/rust_deps.h"

#include <stdio.h>

int main() {
  // let mut argv = Vec::new();
  VecOsString argv = VecOsString_new();
  // argv.push(OsString::from("/bin/cat"));
  VecOsString_push(&argv, OsString_from_str(VR_StrFromCStr("/bin/cat")));
  // argv.push(OsString::from("hello.txt"));
  VecOsString_push(&argv, OsString_from_str(VR_StrFromCStr("hello.txt")));

  // let create_result = Popen::create(&argv, PopenConfig::default());
  PopenResult create_result =
      Popen_create(
          VecOsString_as_slice(&argv),
          PopenConfig_default());

  // let mut process = 
  //   match create_result {
  //     Err(_) => panic!("Failed to open subprocess!"),
  //     Ok(process) => process
  //   };
  if (!PopenResult_is_ok(&create_result)) {
    printf("Failed to open subprocess!\n");
    // Drops implicit in Rust
    PopenResult_drop(create_result);
    VecOsString_drop(argv);
    return 1;
  }
  Popen process = PopenResult_unwrap(create_result);

  // let wait_result = process.wait();
  // if !wait_result.is_ok() {
  //   panic!("Failed to wait on subprocess!");
  // }
  ExitStatusResult wait_result = Popen_wait(&process);
  if (!ExitStatusResult_is_ok(&wait_result)) {
    printf("Failed to wait on subprocess!\n");
    // Drops implicit in Rust
    ExitStatusResult_drop(wait_result);
    Popen_drop(process);
    PopenResult_drop(create_result);
    VecOsString_drop(argv);
    return 1;
  }

  // println!("Success!");
  printf("Success!\n");

  // Drops implicit in Rust
  ExitStatusResult_drop(wait_result);
  Popen_drop(process);
  PopenResult_drop(create_result);
  VecOsString_drop(argv);
  return 0;
}
